### ISSUE TITLE
Error on building ESDK 2016.11 on ubuntu 16.04

### ISSUE THREAD

**Issue by MonteCristo07** [adapteva/epiphany-sdk#74]
I got stuck in this build process. 

********************************************
************ Epiphany SDK Build ************
********************************************

Environment settings:

    ESDK_BUILDROOT=/home/quangnguyen/epiphany-sdk/buildroot
    ESDK_DESTDIR=/home/quangnguyen/epiphany-sdk/buildroot/esdk.2016.11/

Build settings:

    eSDK install directory:       /home/quangnguyen/epiphany-sdk/buildroot/esdk.2016.11/
    eSDK prefix directory:        /opt/adapteva/esdk.2016.11
    Tool chain host prefix:       arm-linux-gnueabihf
    epiphany-libs host prefix:    arm-linux-gnueabihf
    Build version:                2016.11
    Build from branch or tag:     2016.11

Creating the eSDK directory tree...
Logging to /home/quangnguyen/epiphany-sdk/buildroot/logs/2016.11/clone-2018-03-12-1216.log
Cloning gcc...
Cloning binutils...
Cloning gdb...
Cloning newlib...
Cloning cgen...
Downloading gmp...
Downloading mpfr...
Downloading mpc...
Downloading isl...
Downloading ncurses...
Downloading expat...
Cloning epiphany-libs...
Cloning pal...
Download complete
Logging to /home/quangnguyen/epiphany-sdk/buildroot/logs/2016.11/build-2018-03-12-1241.log
START BUILD: Mon Mar 12 05:41:15 PDT 2018
Fetching gcc
Checking out epiphany-gcc-5
Pulling latest version of epiphany-gcc-5
Fetching binutils
Checking out epiphany-binutils-2.27
Pulling latest version of epiphany-binutils-2.27
Fetching gdb
Checking out epiphany-gdb-7.12
Pulling latest version of epiphany-gdb-7.12
Fetching newlib
Checking out epiphany-newlib-2.2.0
Pulling latest version of epiphany-newlib-2.2.0
Fetching cgen
Checking out epiphany-cgen-1.1
Pulling latest version of epiphany-cgen-1.1
Creating unified source tree...
Adding component gcc-infrastructure to unified source
Adding component newlib to unified source
Adding component gdb to unified source
Adding component binutils to unified source
Adding component cgen to unified source
Adding component gcc to unified source
Applying patch: /home/quangnguyen/epiphany-sdk/buildroot/sdk/patches/ncurses-6.0-gcc-5.patch
patching file ncurses/ncurses/base/MKlib_gen.sh
Configuring build machine tool chain...
Building build machine tool chain...
ERROR: Tool chain build for build machine failed.
Build failed. See /home/quangnguyen/epiphany-sdk/buildroot/logs/2016.11/build-2018-03-12-1241.log for details.
The toolchain build failed!

Aborting...

And here is the build error log: 
[build-2018-03-12-1241.log](https://github.com/adapteva/epiphany-sdk/files/1802838/build-2018-03-12-1241.log)

It stops on these: 
libtool: link: cannot determine absolute directory name of `./../zlib'
Makefile:1289: recipe for target 'libbfd.la' failed
make[3]: *** [libbfd.la] Error 1
make[3]: Leaving directory '/home/quangnguyen/epiphany-sdk/buildroot/builds/bd-x86_64-2016.11/bfd'
Makefile:1711: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/quangnguyen/epiphany-sdk/buildroot/builds/bd-x86_64-2016.11/bfd'
Makefile:1187: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/quangnguyen/epiphany-sdk/buildroot/builds/bd-x86_64-2016.11/bfd'
Makefile:2821: recipe for target 'all-bfd' failed
make: *** [all-bfd] Error 2
ERROR: Tool chain build for build machine failed.
But the folder seems still exists and every need files in there. 
Please kindly let me know how to progress from this point. 
Many thanks.

**Comment by Owl3** [comment]
I was stuck on this problem for 3 days. I was running Ubuntu 14.04 - which according to the documentation is an officially supported release. I think it's sad that developers haven't responded to this in 2 months. Here's how i resolved the issue:

**Dependencies:**

apt install build-essential git bison flex libgmp3-dev libncurses-dev libmpc-dev libmpfr-dev texinfo xzip lzip zip
apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
apt install guile-1.8

mkdir buildroot && cd buildroot
git clone --branch 2016.11 https://github.com/adapteva/epiphany-sdk.git sdk
./sdk/build-epiphany-sdk.sh -C -c arm-linux-gnueabihf

**Problem 1:**

Epiphany-SDK installer refuses to work on many Linux distros due to its age. However it will work on ubuntu 14.04.

**Problem 2: (Linkage problems part 1)**

# This will fail with an error about not being able to find ./../zlib directory.
# but the command needs to be run anyway to create the directories.

Copy zlib-1.2.11.tar.gz into the ~/buildroot/builds/bd-x86_64-2016.11/ directory, extract it, rename  the extracted directory to zlib/ and run ./configure, and make.

Comment out line 927 of build-toolchain.sh... the call to a rm -rf, which myopically deletes the directory even when there's no clean option given to the build-epiphany-sdk.sh script. 

Then run:

./sdk/build-epiphany-sdk.sh -c arm-linux-gnueabihf

Do NOT use the -C option the second time as it will delete the zlib you just made!!

Copy the zlib directory into ~/buildroot/builds/bd-armv7l-2016.11.

**Problem 3: (Linkage problems part 2)**

Building the Epiphany-SDK will now fail with ~/buildroot/builds/bd-armv7l-2016.11/gas not recognising file type of libz.so

This is because this version of zlib needs to be cross compiled for ARM, so autotools cannot link it to the rest of the cross compiled binaries. Copy the zlib into the the bd-armv7l-2016.11 directory.

To fix this enter into the zlib directory and run:

CC="arm-linux-gnueabihf-gcc" ./configure

This will tell configure to use an ARM compiler rather than the default x86 compiler.

Then run "make".

Resume with:

./sdk/build-epiphany-sdk.sh -c arm-linux-gnueabihf

Again do NOT use the capitol -C option, else this will delete the cross-compiled zlib.

**Problem 4: (Missing eng.h header)**

There is another problem:

fatal error: eng.h no such file or directory.
#include "eng.h"

in directory ~/buildroot/unisrc-2016.11/sim/epiphany/cpuall.h

being compiled from ~/buildroot/buildss/bd-armv7l-2016.11/sim

The eng.h exists in:

~/buildroot/gdb/sim/sh64/eng.h
~/buildroot/binutils/sim/sh64/eng.h
~/buildroot/unisrc-2016.11/sim/sh64/eng.h

These files are exactly the same. I propose we copy one into the relevant directory.

cp ~/buildroot/gdb/sim/sh64/eng.h ~/buildroot/builds/bd-armv7l-2016.11/sim/epiphany/
cp ~/buildroot/gdb/sim/sh64/eng-compact.h ~/buildroot/builds/bd-armv7l-2016.11/sim/epiphany/
cp ~/buildroot/gdb/sim/sh64/eng-media.h ~/buildroot/builds/bd-armv7l-2016.11/sim/epiphany/

then rerun:

CC="arm-linux-gnueabihf-gcc" ./configure


**Problem 5 (undocumented autotools dependencies in epiphany-libs):**

autoreconf: not found

fixed by "apt install autoconf"


**Problem 6 (Libtool error):**

error: Libtool library used but 'LIBTOOL' is undefined.

apt install libtool
libtoolize

Hopefully if everything has gone well, your epiphany-SDK should now be installed.

**Comment by MonteCristo07** [comment]
Thanks @Owl3 for your solutions. Unfortunately we decided to move forward to another dev. platform because of the coming deadlines. Really appreciated your kindly help.
